### PR TITLE
SDPA-2673 updates tide_media

### PR DESCRIPTION
**Pull request by vincent-gao**
Releasing new tide profile to update tide_media

### Changes
1. added a hook_update to enable the field in form_display of all media bundles.

Jira: https://digital-engagement.atlassian.net/browse/SDPA-2673

more details: https://github.com/dpc-sdp/tide_media/pull/27 and https://github.com/dpc-sdp/tide_media/releases/tag/1.3.1

### CODE REVIEW

**Comment by MdNadimHossain** [comment]
Hi @vincent-gao ,
SDPA-3151- https://github.com/dpc-sdp/tide_media/pull/28, needs to be merged as well in tide_media. Can you please include that with the new version :). Thanks

**Comment by vincent-gao** [comment]
> Hi @vincent-gao ,
> SDPA-3151- [dpc-sdp/tide_media#28](https://github.com/dpc-sdp/tide_media/pull/28), needs to be merged as well in tide_media. Can you please include that with the new version :). Thanks

Please merge it to develop firstly.

**Comment by vincent-gao** [comment]
Also, added dpc-sdp/tide_media#28

**Comment by vincent-gao** [comment]
> @vincent-gao Code changes are approved I'm only marking this as need changes because the base branch should be `master` for releases.

Hi @GROwen, thanks for the CR. I will not merge it directly from `Squash and merge` button. after I get approved, I will use the command line to do a `git flow release finish 1.2.1` and push them with tag from my local. 😬

**Comment by vincent-gao** [comment]
change it 

> @vincent-gao Code changes are approved I'm only marking this as need changes because the base branch should be `master` for releases.

changed based branch to master from github UI.

**Pull request merged**
